### PR TITLE
#US4R-465: Introduced RL-2024-PCie model, some other major changes. 

### PR DESCRIPTION
**Pull request by beatawitek**
Changes and notes are described in the related YouTrack issue. Please also follow the issue during the review..

### CODE REVIEW

**Review by pjarosik — APPROVED** [review]
@beatawitek you have my approval regarding software part of this documentation. 

I have also skimmed through the remaining parts of the documentation, and I didn't find any significant issues, but it should be approved by Mateusz and Marcin.

**Comment by beatawitek** [comment]
@pjarosik In my opinion, it is ready to be merged into the master branch and shared publicly (according to the Marcin's naming convention, it will be v.7.0).

**Comment by heymarcin** [comment]
Some tiny revisions committed to the branch (@beatawitek Pls Review!). 
ITEMS/CLARIFICATIONS NEEDED:
* 2_hardware.md -- Digital I/O ports << added 10MHz refrence clock
* 4_first-use.md -- Caution: "The power cable should be plugged into the 120V,60Hz or 230V,50Hz mains power supply with a protective bonding." -- should be active or commented?
* what is this file -- docs/content/IMG_20241009_085052.xcf?

**Comment by beatawitek** [comment]
> Some tiny revisions committed to the branch (@beatawitek Pls Review!). ITEMS/CLARIFICATIONS NEEDED:
> 
> * 2_hardware.md -- Digital I/O ports << added 10MHz refrence clock
BW: OK if true

> * 4_first-use.md -- Caution: "The power cable should be plugged into the 120V,60Hz or 230V,50Hz mains power supply with a protective bonding." -- should be active or commented?
BW: This should be commented. The us4R-lite has a 'two-wire' power plug, so in my opinion, it doesn't make sense to retain this requirement in the user manual.

> * what is this file -- docs/content/IMG_20241009_085052.xcf?
BW: origin file (Gimp) for all .png exports (back-side view of the us4R-lite)

**Review by heymarcin — APPROVED** [review]
Approved!

**Comment by beatawitek** [comment]
last minute changes- version history and footer - do not require additional review - ready for merging

**Pull request merged**
